spring.application.name=Smart Farming Assistant

spring.datasource.url=jdbc:postgresql://localhost:54324/smart_farming_db
spring.datasource.username=sf_admin
spring.datasource.password=sf_admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=SW325WFDEY564748IWBHHSWW6EUEHNWU465527483EHWN
jwt.expiration=3600000
jwt.header=Authorization
jwt.token-prefix=Bearer 

openmeteo.forecast.base-url=https://api.open-meteo.com
openmeteo.geocoding.base-url=https://geocoding-api.open-meteo.com