spring.application.name=Smart Farming Assistant
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.header=Authorization
jwt.token-prefix=Bearer

openmeteo.forecast.base-url=https://api.open-meteo.com
openmeteo.geocoding.base-url=https://geocoding-api.open-meteo.com

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.1-8b-instant

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false

google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}
google.refresh.token=${GOOGLE_REFRESH_TOKEN}
google.sender.email=${GOOGLE_SENDER_EMAIL}
